version: '3.8'

services:
  tikz-mcp-server-minimal:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: ${CONTAINER_NAME:-tikz-mcp-server-minimal-container}
    ports:
      - "${PORT:-3001}:3000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      # 可选：挂载字体目录（如有自定义字体）
      - ./fonts:/app/fonts:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:3000/mcp/', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s